FROM python:3.11

RUN apt-get update \
    && apt-get clean; rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /usr/share/doc/*
RUN apt install git
RUN git config --global user.email "premanshu.mukherji@maersk.comm"
RUN git config --global user.name "prem-mukherji"

RUN pip install --upgrade pip
RUN pip install weasyprint
RUN pip install markdown2
RUN pip install pyyaml
RUN pip install GitPython

RUN mkdir /application
WORKDIR "/application"
ADD Chatbot1/sirius-feeder.py /application/
ADD Chatbot1/subscriberInfo.yaml /application/

ENV GITHUB_SERVICE_ACCOUNT=GITHUB_SERVICE_ACCOUNT
ENV GITHUB_SERVICE_ACCOUNT_TOKEN=GITHUB_SERVICE_ACCOUNT_TOKEN
RUN touch /env.txt
RUN printenv > /env.txt

CMD [ "python", "sirius-feeder.py" ]